Repository alboompro/boom-components, pull requests merged in 2020-01, with the labels that each got.

#16 Issue/alboom 5
  package-lock.json
  package.json
Labels: dependencies

#17 Improv/notification add icon
  src/feedback/notification/Notice.js
  src/feedback/notification/Notification.js
  src/feedback/notification/styles.js
Labels: enhancement

#18 Fix/modal prop floating style
  package.json
  size-snapshot.json
  src/data-display/modal/styles.js
Labels: bug
